services:
  postgres:
    image: postgres:16-alpine
    container_name: relib-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: relib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
